version: "3"

services:
  cli:
    build: ./docker/cli
    volumes:
      - ./todo:/var/www
    working_dir: /var/www
    extra_hosts:
      - "mysql:172.31.16.166"
  fpm:
    build: ./docker/fpm
    volumes:
      - ./todo:/var/www
    extra_hosts:
      - "mysql:172.31.16.166"
  nginx:
    image: nginx:1.17
    volumes:
      - ./todo:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - fpm
    ports:
      - 8000:80
